### ISSUE TITLE
Support for Fhem-MQTT2 light devices

### ISSUE THREAD

**Issue by R1k4rd** [dominikkarall/gassistant-fhem-firebase#1]
jsonlist2:

{
  "Arg":"lichtSchrank",
  "Results": [
  {
    "Name":"lichtSchrank",
    "PossibleSets":"on:noArg off:noArg brightness:colorpicker,BRI,0,5,255 color_temp:colorpicker,CT,154,2,500 color:colorpicker,RGB on-for-timer on-till intervals off-for-timer off-till on-till-overnight blink off-till-overnight toggle attrTemplate:?,A_00_MQTT2_CLIENT_general_bridge,A_01_tasmota_basic,A_01a_tasmota_basic_state_power1,A_01b_tasmota_1ch+motion+SI7021,A_01c_tasmota_POW,A_01x_tasmota_clear_readings_reset_readingsList_and_reboot,A_01x_tasmota_prefix_clearing_and_reboot,A_01z_tasmota_set_lowercase_texts_and_state1,A_01z_tasmota_set_power1_state_to_power,A_01z_tasmota_set_uppercase_texts_and_state1,A_02_tasmota_2channel_split,A_02a_tasmota_2ch_unified,A_04a_tasmota_4ch_unified_basic_text,A_04b_tasmota_4ch_unified_icon,A_05a_tasmota_rgb_led_controller,A_10_shelly1,A_10a_shellyplug,A_11a_shelly2_split,A_11b_shelly2_roller,A_14a_shelly4pro_split,A_14b_shelly4pro_unified,A_15_shellybulb,A_16_shellyht,L_01_zigbee2mqtt_bridge,L_01a_zigbee2mqtt_bridge_0x,L_01x_zigbee2mqtt_bridge_outdated,L_02a_zigbee2mqtt_light_dimmer,L_02b_zigbee2mqtt_light_cct,L_02c_zigbee2mqtt_light_rgb_hex,L_02c_zigbee2mqtt_light_rgb_rgb,L_02d_zigbee2mqtt_light_rgbw_hex,L_02d_zigbee2mqtt_light_rgbw_rgb,L_02e_zigbee2mqtt_light_rgbcct_hex,L_02e_zigbee2mqtt_light_rgbcct_rgb,L_03_zigbee2mqtt_smokeDetector,L_04_zigbee2mqtt_hueMotionSensor,L_05_zigbee2mqtt_smart+plug,L_06_zigbee2mqtt_ContactSensor,L_07_zigbee2mqtt_TempHumHpaSensor,L_08_zigbee2mqtt_Human_Motion_Sensor,L_09_zigbee2mqtt_Motion_Sensor,L_10_zigbee2mqtt_Water_Leak_Sensor,L_11_zigbee2mqtt_Light_Switch,X_01_esp_milight_hub_bridge,X_01_esp_milight_hub_rgbw_bulb,X_01a_esp_milight_hub_make_rgbw_group,X_01a_esp_milight_hub_rgb_cct_bulb,X_01b_esp_milight_hub_cct_only_bulb,X_01x_esp_milight_hub_max_features_bulb",
    "PossibleAttrs":"alias comment:textField-long eventMap:textField-long group room suppressReading userReadings:textField-long verbose:0,1,2,3,4,5 IODev autocreate:0,1 bridgeRegexp:textField-long devicetopic devPos disable:0,1 disabledForIntervals getList:textField-long imageLink jsonMap:textField-long model readingList:textField-long setList:textField-long setStateList event-aggregator event-min-interval event-on-change-reading event-on-update-reading oldreadings stateFormat:textField-long timestamp-on-change-reading assistantName:textField cmdIcon devStateIcon:textField-long devStateStyle gassistantName:textField genericDeviceType:security,ignore,switch,outlet,light,blind,thermometer,thermostat,contact,garage,window,lock,aircondition,airpurifier,camera,coffeemaker,dishwasher,dryer,fan,kettle,oven,refrigerator,scene,sprinkler,vacuum,washer homebridgeMapping:textField-long icon realRoom:textField sortby webCmd webCmdLabel:textField-long widgetOverride userattr",
    "Internals": {
      "CID": "zigbee_rgbcct01",
      "DEF": "zigbee_rgbcct01",
      "DEVICETOPIC": "lichtSchrank",
      "FUUID": "5c656d8a-f33f-3868-a1ec-b0833bc79fb6ecfb",
      "LASTInputDev": "mqttServer",
      "MSGCNT": "12",
      "NAME": "lichtSchrank",
      "NR": "95",
      "STATE": "on",
      "TYPE": "MQTT2_DEVICE",
      "mqttServer_MSGCNT": "12",
      "mqttServer_TIME": "2019-02-27 22:19:42"
    },
    "Readings": {
      "associatedWith": { "Value":"mqttZigbee", "Time":"2019-02-14 14:30:50" },
      "brightness": { "Value":"255", "Time":"2019-02-27 13:55:40" },
      "color": { "Value":"ffff5e", "Time":"2019-02-27 13:55:44" },
      "color_temp": { "Value":"154", "Time":"2019-02-27 14:16:06" },
      "color_x": { "Value":"0.427", "Time":"2019-02-27 22:19:42" },
      "color_y": { "Value":"0.49", "Time":"2019-02-27 22:19:42" },
      "state": { "Value":"on", "Time":"2019-02-27 22:19:42" }
    },
    "Attributes": {
      "IODev": "mqttServer",
      "devStateIcon": "{zigbee2mqtt_devStateIcon255($name)}",
      "gassistantName": "Licht Schrank",
      "genericDeviceType": "light",
      "group": "Beleuchtung",
      "model": "L_02e_zigbee2mqtt_light_rgbcct_rgb",
      "readingList": "zigbee2mqtt/rgbcct01:.* { json2nameValue($EVENT) }",
      "realRoom": "Richard",
      "room": "Beleuchtung,Sprachsteuerung",
      "setList": "on:noArg zigbee2mqtt/rgbcct01/set {\"state\":\"ON\"}\n  off:noArg zigbee2mqtt/rgbcct01/set {\"state\":\"OFF\"}\n  brightness:colorpicker,BRI,0,5,255 zigbee2mqtt/rgbcct01/set {\"state\":\"on\",\"$EVTPART0\":\"$EVTPART1\"}\n  color_temp:colorpicker,CT,154,2,500 zigbee2mqtt/rgbcct01/set {\"$EVTPART0\":\"$EVTPART1\"}\n  color:colorpicker,RGB {\"zigbee2mqtt/rgbcct01/set \".zigbee2mqtt_RGB2JSON($EVTPART1)}",
      "setStateList": "on off",
      "stateFormat": "{lc ReadingsVal(\"$name\",\"state\",0)}",
      "userReadings": "state {if(ReadingsVal($name,\"state\",\"\") eq \"OFF\") {return \"off\"} else {return \"on\"}},\nbrightness {(split ' ',ReadingsVal($name,\"brightness\",0))[1]},\ncolor {(split ' ',ReadingsVal($name,\"color\",0))[1]},\ncolor_temp {(split ' ',ReadingsVal($name,\"color_temp\",0))[1]},",
      "webCmd": "brightness:color_temp:color:color_temp 500:color_temp 346:color_temp 154"
    }
  }  ],
  "totalResultsReturned":1
}

**Comment by dominikkarall** [comment]
Erledigt, die Erkennung der Lampe habe ich auf Basis der moeglichen Befehle implementiert (color, color_temp, brightness).
